name: Dispatcher

on:
  push:
    branches:
      - main

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: version
        run: echo "::set-output name=version::$(cat version | cut -d ':' -f2 | awk '{$1=$1};1')"
        id: version
        
      - name: build artifacts
        run: zip -r maeno.zip .
        
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Maeno-${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./maeno.zip
          asset_name: maeno.zip
          asset_content_type: application/zip
        
      - name: clean artifact
        run: rm -f ./maeno.zip
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kshithija/maeno-hq-01:${{ steps.version.outputs.version }}
          
      - name: send dispatch
        run: "curl \"https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW/dispatches\" -s -H \"Authorization: Token $TOKEN\" -d \"{ \\\"ref\\\":\\\"main\\\", \\\"inputs\\\": { \\\"version_id\\\": \\\"$VERSION\\\"} }\""
        env:
          OWNER: Maeno-HQ
          REPO: Maeno-infra
          WORKFLOW: 15089213
          VERSION: ${{ steps.version.outputs.version }}
          TOKEN: ${{ secrets.REPO_TOKEN }}

